#!/bin/bash
#
#SBATCH --array=1-3
#SBATCH --job-name=matlab_UTP
#SBATCH --output=matlab_UTP."%j".out
#SBATCH --error=matlab_UTP."%j".err
#SBATCH --cpus-per-task=6
#SBATCH --mem=16G
#SBATCH --time=02:00:00
#SBATCH --verbose
#SBATCH -p serc
module load matlab

matlab -nodisplay < UTP_Job.m
